"use client";

import { useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { useCourse } from "@/hooks/useCourse";
import { useSummaryStatus } from "@/hooks/useSummaryStatus";
import { useCourseSummary } from "@/hooks/useCourseSummary";
import { useLectureSummary } from "@/hooks/useLectureSummary";
import { GlassCard } from "@/components/ui/GlassCard";
import { CourseSummaryCard } from "@/components/summaries/CourseSummaryCard";
import { LectureSummaryPicker } from "@/components/summaries/LectureSummaryPicker";
import { LectureSummaryPanel } from "@/components/summaries/LectureSummaryPanel";

export default function SummariesPage() {
  const { activeCourse } = useCourse();
  const status = useSummaryStatus();
  const courseSummary = useCourseSummary();

  const [selectedLectureId, setSelectedLectureId] = useState<number | null>(
    null
  );
  const [trackedCourseId, setTrackedCourseId] = useState(activeCourse.id);

  // Clear selection when the course changes — same render-time pattern as
  // transcripts/page.tsx and workspace/page.tsx.
  if (trackedCourseId !== activeCourse.id) {
    setTrackedCourseId(activeCourse.id);
    setSelectedLectureId(null);
  }

  const lectureSummary = useLectureSummary(selectedLectureId);
  const selectedLecture =
    status.data?.lectures.find((l) => l.lecture_id === selectedLectureId) ??
    null;

  function handleSelect(lectureId: number) {
    setSelectedLectureId(lectureId);
  }

  function handleGenerateLectureSummary(refresh = false) {
    lectureSummary.generate(refresh);
  }

  // Mark the picker badge cached the moment a generation succeeds, without
  // waiting for a full /summary/status refetch — same pattern as
  // useLectures.markLectureCached on the Transcripts/Workspace tabs.
  if (
    lectureSummary.data &&
    selectedLectureId !== null &&
    selectedLecture &&
    !selectedLecture.summary_cached
  ) {
    status.markSummaryCached(selectedLectureId);
  }

  return (
    <section className="lg:h-full lg:flex lg:flex-col">
      <div className="px-1 mb-5 shrink-0">
        <h1 className="text-2xl font-bold text-white tracking-tight">
          AI Summaries
        </h1>
        <p className="text-sm text-white/45 mt-1">
          Course-level and per-lecture summaries generated by Groq for{" "}
          <span className="text-indigo-300 font-medium">
            {activeCourse.title}
          </span>
          .
        </p>
      </div>

      <div className="mb-3 shrink-0">
        <CourseSummaryCard
          data={courseSummary.data}
          loading={courseSummary.loading}
          error={courseSummary.error}
          onGenerate={courseSummary.generate}
        />
      </div>

      {status.loading && (
        <div className="flex-1 grid place-items-center">
          <p className="text-sm text-white/40">Loading lectures…</p>
        </div>
      )}

      {!status.loading && status.error && (
        <GlassCard
          animate
          className="flex flex-col items-center text-center gap-3 py-16 px-8"
        >
          <AlertTriangle className="h-8 w-8 text-amber-300" />
          <div className="space-y-1">
            <h2 className="text-sm font-semibold text-white">
              Couldn&rsquo;t load lectures
            </h2>
            <p className="text-xs text-white/45 max-w-sm">{status.error}</p>
          </div>
          <button
            onClick={status.refetch}
            className="mt-1 inline-flex items-center gap-2 rounded-xl grad-accent px-4 py-2 text-sm font-semibold text-white hover:opacity-90 transition glow"
          >
            <RefreshCw className="h-4 w-4" /> Try again
          </button>
        </GlassCard>
      )}

      {!status.loading && !status.error && status.data && (
        <div className="flex flex-col lg:flex-row gap-3 lg:flex-1 lg:min-h-0">
          <LectureSummaryPicker
            lectures={status.data.lectures}
            selectedLectureId={selectedLectureId}
            onSelect={handleSelect}
          />
          <LectureSummaryPanel
            selectedLecture={selectedLecture}
            summary={lectureSummary.data}
            loading={lectureSummary.loading}
            error={lectureSummary.error}
            onGenerate={handleGenerateLectureSummary}
          />
        </div>
      )}
    </section>
  );
}
